import discord
# Colors array for randomly selecting a color for embeds
colors = [
    discord.Color.teal(),
    discord.Color.dark_teal(),
    discord.Color.green(),
    discord.Color.dark_green(),
    discord.Color.blue(),
    discord.Color.dark_blue(),
    discord.Color.purple(),
    discord.Color.dark_purple(),
    discord.Color.magenta(),
    discord.Color.dark_magenta(),
    discord.Color.gold(),
    discord.Color.dark_gold(),
    discord.Color.orange(),
    discord.Color.dark_orange(),
    discord.Color.red(),
    discord.Color.dark_red(),
    discord.Color.lighter_grey(),
    discord.Color.dark_grey(),
    discord.Color.light_grey(),
    discord.Color.darker_grey(),
    discord.Color.blurple(),
    discord.Color.greyple(),
]
